### ISSUE TITLE
Can't see notification text in 2.0

### ISSUE THREAD

**Issue by mweber03** [Tautulli/Tautulli-Remote#107] opened 2021-03-24 15:36 UTC
With the new app, I can't see notifications anymore. I'll get a push notification to my phone that says "Tautulli Notification" (in the old app it actually had the notification text). Then when I click the notification, it brings me to the Activity page on that app, which only has what is playing. There doesn't seem to be a way to actually see the notification text anymore. 

 - Mobile Device: Pixel 2
 - Mobile OS: Android 11
 - Tautulli Remote Version: 2.5.0
 - Tautulli Version: 2.6.10

**Comment by TheMeanCanEHdian** [comment] 2021-03-24 15:47
Please check [this wiki entry](https://github.com/Tautulli/Tautulli-Remote/wiki/Troubleshooting#my-notifications-arent-working) on how to solve this.

Duplicate of #95

**Closed by TheMeanCanEHdian** 2021-03-24 15:48 UTC
Labels: bug

**Comment by mweber03** [comment] 2021-03-24 16:35
Thanks!
