### ISSUE TITLE
ETA leaves out a digit in time

### ISSUE THREAD

**Issue by Redhawk2000** [Tautulli/Tautulli-Remote#105] opened 2021-03-14 22:27 UTC
**Describe the bug**
When an item is being played and its finishing time (ETA) is less than 10 minutes after the hour, the timestamp will look like the screenshot below.

**Expected behavior**
Showing all the digits of time.

**Screenshots**
The ETA in the screenshot should be 20:03 instead of 20:3.

**Tautulli Info (please complete the following information):**
 - Mobile Device: Asus Zen6
 - Mobile OS: Android 11 (though the player doesn't matter. Happens on roku as well)
![Screenshot_20210314-181539006_1](https://user-images.githubusercontent.com/18142543/111086507-c959f500-84f2-11eb-8053-f74d1b6de9ac.jpg)

 - Tautulli Remote Version 2.4.4
 - Tautulli Version 2.6.8

**Additional context**

**Comment by TheMeanCanEHdian** [comment] 2021-03-14 22:29
Duplicate of #103

**Closed** 2021-03-14 22:29 UTC
Labels: bug, duplicate
