### ISSUE TITLE
Display count of active streams

### ISSUE THREAD

**Issue by nomadore** [Tautulli/Tautulli-Remote#146] opened 2021-08-31 20:59 UTC
### What is your feature request?

It would be nice to be able to see on the home page of the app many streams are currently going on.  That's usually the first thing I look at when I view the Tautulli web version.

**Comment by TheMeanCanEHdian** [comment] 2021-08-31 21:01
Duplicate of #126 please give that request a thumbs up to add your vote to it!

**Closed by TheMeanCanEHdian** 2021-08-31 21:01 UTC
Labels: enhancement
