### ISSUE TITLE
Generic Notification for Plex Up/Down and Plex Remote Access Up/Down

### ISSUE THREAD

**Issue by ytosaas** [Tautulli/Tautulli-Remote#223] opened 2023-10-22 23:35 UTC
### Describe the bug

The Tautulli Remote app gets generic notifications for Plex Up/Down and Plex Remote Access Up/Down.

All other notifications seems to be working fine (received a successfully Recently Added notification)

Removed remote devices from Tautulli and re-registered.

Reproduced by SwiftPanda on Discord

### Steps to Reproduce

Enable Remote App notifications
Enable Plex Up/Down and Plex Remote Access Up/Down triggers
Shutdown Plex server and restart to trigger notifications

### Expected Behavior

Successful notification vs generic notification

### Tautulli Remote Version

v3.1.0

### Tautulli Version

v2.12.2

### Mobile Device

Samsung Galaxy S23 Ultra

### Mobile OS

Android 13

**Comment by TheMeanCanEHdian** [comment] 2023-10-23 15:36
I am unable to reproduce this issue. I will add some code to the next release to allow for additional insight on the notification process to be logged. These logs will have to be grabbed using logcat/xcode for android/ios however.

![Screenshot_20231023_100936_Discord](https://github.com/Tautulli/Tautulli-Remote/assets/16025103/8925539b-06df-45fc-a23e-c36410403471)

**Comment by TheMeanCanEHdian** [comment] 2023-10-27 17:19
This issue was related to timeouts when images were enabled, but no image was provided. A fix is in v3.2.1 which will roll out over the coming days. If you are having this issue you can disable notification images as a workaround until you update.

**Closed by TheMeanCanEHdian** 2023-10-27 17:19 UTC
Labels: bug
