### ISSUE TITLE
Primary connection input does not accept local hostname

### ISSUE THREAD

**Issue by DGamesta** [Tautulli/Tautulli-Remote#208] opened 2023-06-27 22:34 UTC
### Describe the bug

When adding a Primary connection url for tautulli, the input field does not accept a local hostname as a valid input and says "Enter a valid URL format". 

### Steps to Reproduce

Go to settings
Click server
Click primary connection 
Enter in a local hostname such as "https://tautulli"
Observe "Enter a valid URL format" message.

### Expected Behavior

I would expect local hostnames to work. Only supporting a FQDN and not the local hostname can run into issues with reverse proxy's expecting a certain ingress. So long as DNS knows what to do with it, it shouldn't be Tautulli's responsibility to verify that url syntax.

### Tautulli Remote Version

3.0.3

### Tautulli Version

2.12.4

### Mobile Device

Pixel 6

### Mobile OS

Android 13

**Comment by JonnyWong16** [comment] 2023-06-27 22:45
Duplicate of #202.

**Comment by samwiseg0** [comment] 2023-06-27 22:45
Duplicate of https://github.com/Tautulli/Tautulli-Remote/issues/202

**Closed** 2023-06-27 22:46 UTC
Labels: bug, needs-review
