### ISSUE TITLE
Crashes on deleted libraries

### ISSUE THREAD

**Issue by almostepic89** [Tautulli/Tautulli-Remote#63] opened 2018-07-07 11:53 UTC
Web front end has only 2 of the 4 libraries setup in my Plex server (manually deleted 2 so they would not be tracked by deleting from the libraries list) but the app lists all 4 libraries anyways.

Upon clicking either of the two that had been deleted from the web front end the app crashes to home screen

**Comment by JonnyWong16** [comment] 2018-07-07 13:19
This is not a bug. Data is never automatically deleted from Tautulli because someone may want to keep the history of deleted libraries. If you don't care about the data then you can manually delete them from Tautulli.

It will redirect to the homepage if the user logged into Tautulli does not have permissions to access that library. Since it was deleted from Plex then the user obviously doesn't have permission. The admin user can always access all library pages.

**Comment by almostepic89** [comment] 2018-07-07 13:53
@JonnyWong16 The 2 libraries being monitored by Tautulli were manually removed by the admin and while logged in to Tautulli Remote it still shows the 2 libraries. 

Steps to reproduce bug
1) Login to Tautulli from PC/Mobile Browser
2) Go to Libraries tab and click the edit button.
3) Select the Delete button next to 1 or more libraries, and then exit Edit mode to confirm deletion from Tautulli.
4) Load the Tautulli Remote app
5) In the app go to the Libraries menu which will still list the removed library.
6) Click on the removed library, and the Tautulli Remote app crashes back to Android home screen.

**Comment by JonnyWong16** [comment] 2018-07-07 13:57
Oh you're taking about the Android app. You are in the wrong place.

https://github.com/Tautulli/Tautulli-Remote

**Comment by almostepic89** [comment] 2018-07-07 14:00
Pretty sure that is the repo that is listed at the top of this issue report.

https://imgur.com/a/JYGYT3r

**Comment by JonnyWong16** [comment] 2018-07-07 14:00
My mistake.

**Comment by TheMeanCanEHdian** [comment] 2021-03-08 16:27
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose

**Closed by TheMeanCanEHdian** 2021-03-08 16:27 UTC
