### ISSUE TITLE
Tautulli/Plex update notification is blank

### ISSUE THREAD

**Issue by aw9d** [Tautulli/Tautulli-Remote#95] opened 2021-03-09 21:09 UTC
**Describe the bug**
I get a notification and go to check it but nothing is displayed. Both notifications were for updates to Plex and Tautulli apps 

**To Reproduce**
1. Click on notification from Tautulli 2.0 app to open Tautulli
2. Nothing is displayed. 

**Expected behavior**
In the drop down on my Android phone or in the app I would expect to see information regarding the updates from Plex and Tautulli.

**Screenshots**
Did not capture screenshots. 

**Tautulli Info (please complete the following information):**
 - Mobile Device: Pixel 4a.
 - Mobile OS: Android 11
 - Tautulli Remote Version 2.4.0
 - Tautulli Version 2.6.8
**Additional context**
None.

**Comment by aw9d** [comment] 2021-03-09 22:00
Yes that is correct. And also this one. 

![image](https://user-images.githubusercontent.com/58528465/110543894-21a28880-80e8-11eb-9fba-011043d11338.png)

**Comment by TheMeanCanEHdian** [comment] 2021-03-09 22:30
If you can grab a screenshot the next time you see one of these notifications.

**Comment by aw9d** [comment] 2021-03-09 23:03
I will next time Tautalli or Plex gets an update. I just updated both on my NAS today. 

Movies/TV shows seem to be working normally. When I check my app info for notifications I have Server Notifications which are my movies/tv and Miscellaneous which was the one that didn't have any info at all.

**Comment by TheMeanCanEHdian** [comment] 2021-03-10 01:00
Do you happen to have the old app installed still?

**Comment by aw9d** [comment] 2021-03-10 01:19
No. But I did notice the old phone from the old app was still on the list under the mobile app section. I removed it.

**Comment by TheMeanCanEHdian** [comment] 2021-03-10 01:21
Okay, we were unable to reproduce this on our side. I'm going to close this for now but re-open it if you are able to reproduce or run into the issue again.

**Closed** 2021-03-10 01:22 UTC
Labels: bug

**Comment by JonnyWong16** [comment] 2021-03-10 05:56
Commenting for reference.

This is due to the encryption key for the device changing when you register a new device. Make sure you update your notification agents to select the new device.

![image](https://user-images.githubusercontent.com/9099342/110583109-08b6c900-8122-11eb-939c-2bd1f2a86d31.png)

**Comment by sm753** [comment] 2021-09-01 04:01
![Screenshot_20210831-225010](https://user-images.githubusercontent.com/89892213/131609165-70c74c99-35ab-47aa-b5df-e6c183fb3832.png)

I'm new to Github, I see this issue is closed, but I figure it may be better to add here instead of opening a new issue/bug report? Sorry if this is not the protocol for issue reporting.

I'm having a similar issue, please see the attached screenshot. Switched to a new phone recently, installed app and set up in Tautulli. Instead of notifications containing text/information, they now just show as "Tautulli Notification".

Referencing the comment above, I made sure to update the notifications agents to my new device. Trying to troubleshoot - I removed my old device from Tautulli entirely. Cleared app data on my phone, and re-registered my new phone again. Still the same issue.

Mobile Device: Pixel 5a.
Mobile OS: Android 11
Tautulli Remote Version 2.12.1
Tautulli Version 2.7.6

**Comment by TheMeanCanEHdian** [comment] 2021-09-01 13:05
Hey @sm753 we use [our Discord](https://tautulli.com/discord.html) for support.

Since you've said you've tried the above already it's best if you swing by the Discord, and we'll help see what the issue is.

**Comment by sm753** [comment] 2021-09-08 14:30
> Hey @sm753 we use [our Discord](https://tautulli.com/discord.html) for support.
> 
> Since you've said you've tried the above already it's best if you swing by the Discord, and we'll help see what the issue is.

Thank you for the reply. FYI if you were interested in knowing - I literally did nothing and the issue went away a few days later. App notifications are now working as intended. Not sure what the issue was.
