### ISSUE TITLE
Text in Activity Sheet buttons overflows with different screen/text sizes

### ISSUE THREAD

**Issue by holl595** [Tautulli/Tautulli-Remote#205] opened 2023-06-22 19:24 UTC
### Describe the bug

On an iPhone 13, if the text is set to the default size the terminate stream button is hidden. 

![IMG_3832](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/0932b89c-7b8d-4e75-85be-1719b6d664bc)
![IMG_3833](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/fe1ebd1b-7395-4e8f-a90a-e84552c882b0)

If the text size is reduced all the buttons are visible but the text is out of centre

![IMG_3834](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/ea2497a0-aff3-404f-8aa2-a9d9b833b659)
![IMG_3835](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/ac9f1ea0-e077-404e-9111-0fc2e97c36a8)

### Tautulli Remote Version

3.0.3

### Tautulli Version

2.12.4

### Mobile Device

iPhone 13

### Mobile OS

iOS 16.5

**Comment by TheMeanCanEHdian** [comment] 2023-06-22 20:26
I am able to reproduce the button text overflowing due to screen size. This is a challenging item to address due to the various settings that can affect it.

I am not able to reproduce the terminate button not appearing. Text size does not have any influence on that. I suspect Tautulli reported the stream in a way that Tautulli Remote did not have the info needed to actually terminate the stream.

Please let me know if you have reliable steps to reproduce the terminate button not appearing when it should.

**Comment by holl595** [comment] 2023-06-22 20:47
I’ve tried to reproduce the missing button but am now not able to either. 

The text being centred was never an issue on the old version. 
![IMG_3836](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/98184557-589b-46a1-85ac-7ad7d83378c0)

**Comment by TheMeanCanEHdian** [comment] 2023-06-22 20:59
The issue is that the text is technically centered it is just overflowing. A consequence of putting the buttons all on the same row. I will rename this issue about coming up with a better way to solve that particular issue.

**Comment by holl595** [comment] 2023-08-02 07:04
This seems to be fixed in the latest v3.0.4

![IMG_4016](https://github.com/Tautulli/Tautulli-Remote/assets/72844000/617d47e7-170a-4c9e-84c3-45912871226a)

**Comment by TheMeanCanEHdian** [comment] 2023-08-02 12:33
Yes this change went live in 3.0.4. Forgot to close this out.

**Closed** 2023-08-02 12:33 UTC
Labels: bug, priority:normal
